export enum IconName {
  home = 'home',
  cart = 'cart',
  like = 'like',
  bell = 'bell',
  menu = 'menu',
  search = 'search',
  star = 'star',
  close = 'close',
  left = 'left',
  bean = 'bean',
  beans = 'beans',
  location = 'location',
  drop = 'drop',
  add = 'add',
  minus = 'minus',
  wallet = 'wallet',
  chip = 'chip',
  visa = 'visa',
}
